dist:
  module: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol
  name: otelcontribcol
  description: Local OpenTelemetry Collector Contrib binary, testing only.

  version: 0.116.0-dev

extensions:

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.116.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.116.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.116.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatorateprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/geoipprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/intervalprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/logdedupprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricsgenerationprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/sumologicprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.116.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/remotetapprocessor v0.116.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/nopreceiver v0.116.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.116.0

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.116.0
  - gomod: github.com/RononDex/profilestotracesconnector v0.0.1-dev

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.19.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.19.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.19.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.19.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.19.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/confmap/provider/s3provider v0.113.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/confmap/provider/secretsmanagerprovider v0.113.0

replaces:
# a list of "replaces" directives that will be part of the resulting go.mod

# This replace statement is necessary since the newly added component is not found/published to GitHub yet. Replace references to GitHub path with the local path
  - github.com/RononDex/profilestotracesconnector => /home/cobra/dev/ip6-code/src/opentelemetry-profiles-to-traces-connector/
