dist:
  module: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol
  name: otelcontribcol
  description: Local OpenTelemetry Collector Contrib binary, testing only.
  output_path: ./otelcol-dev
  version: 0.112.0-dev

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.115.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.115.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.115.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter v0.115.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.115.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.115.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/nopreceiver v0.115.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.115.0

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.115.0
  - gomod: github.com/RononDex/profilestotracesconnector v0.115.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.19.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.19.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.19.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.19.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.19.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/confmap/provider/s3provider v0.113.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/confmap/provider/secretsmanagerprovider v0.113.0

replaces:
# a list of "replaces" directives that will be part of the resulting go.mod

# This replace statement is necessary since the newly added component is not found/published to GitHub yet. Replace references to GitHub path with the local path
  - github.com/RononDex/profilestotracesconnector => ../
