receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # NOTE: Prior to v0.86.0 use the `logging` instead of `debug`.
  debug:

connectors:
  profilestotraces:

service:
  pipelines:
    profiles:
      receivers: [otlp]
      exporters: [profilestotraces]
    traces:
      receivers: [profilestotraces]
      exporters: [debug]
